name: Clear Commit History

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1,7 *'

jobs:
  clear-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clear commit history for all branches
        run: |
          remote_branches=$(git branch -r | grep -v 'HEAD' | sed 's/origin\///')
          echo "Found branches: $remote_branches"

          for branch in $remote_branches; do
            echo "Processing branch: $branch"
            git checkout $branch
            git checkout --orphan temp
            git add -A
            git commit --allow-empty -m "Initial commit with cleared history for branch: $branch"
            git push -f origin temp:$branch
            git checkout $branch
            git branch -D temp
          done
